### ISSUE TITLE
Create myclasses.php page

### ISSUE THREAD

**Issue by Sum4196** [ajwhite2206/courses_php#10]
myclass.php page should show classes that the person is registered for

**Comment by AmjadOmar** [comment]
Every course the user registered at should have a button or a link take the student to the course evaluation page.

**Comment by AmjadOmar** [comment]
This should be available only to logged in users.

**Comment by Sum4196** [comment]
The links are setup to be like this: ".../survey.php?CID=#" the # denotes the courseID number.  survey.php simply needs to use the CID variable to specify the course.
