### ISSUE TITLE
Create Register Column

### ISSUE THREAD

**Issue by ajwhite2206** [ajwhite2206/courses_php#11]
It will be under the Course table.

**Comment by AmjadOmar** [comment]
Plus button to register. This should be available only to logged in users.

**Comment by ajwhite2206** [comment]
Will if you want to make the table again for me I can hook up the PHP part of it?

**Comment by Sum4196** [comment]
The register column has been created by @weonthank , however there needs to be some work done with the Course_registration.php file and has been posted as another issue.
