### ISSUE TITLE
Get full file package uploaded and working on server.

### ISSUE THREAD

**Issue by ajwhite2206** [ajwhite2206/courses_php#6]
Login, Passreset, courses, etc all need to be working and interacting on the server.

**Comment by AmjadOmar** [comment]
Where we at here?

**Comment by Sum4196** [comment]
I'm working on it right now

**Comment by AmjadOmar** [comment]
I just pushed my latest updates make sure to include them for tomorrow show.

**Comment by Sum4196** [comment]
I just downloaded it, but I download it again
