### ISSUE TITLE
Account setup

### ISSUE THREAD

**Issue by Sum4196** [ajwhite2206/courses_php#8]
Signup needs to also add in the name, department, office,  and phone in the database at creation.  If these values are not needed, then we can close this issue.

**Comment by AmjadOmar** [comment]
Signup feature is not required right now.

**Comment by Sum4196** [comment]
Okay, I wasn't sure.  I'm not sure what I did, but I was testing the other php pages and somehow I managed to break the website on my local machine where every link I clicked would redirect me to the index.php page, except the courses.php file.  For some reason courses.php still would load, but not others.  I don't know if you have any idea why that would happen or how to avoid the issue, but I'm sure we can figure that one out later.

**Comment by AmjadOmar** [comment]
Because you're logged in. Browse logout.php page and you will be signed out.

**Comment by Sum4196** [comment]
Okay, thank you
